apiVersion: v1
kind: ReplicationController  # TODO: this should not be rc.  Only 1 beat can exist per pod.
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: 1
  selector:
    name: celery-beat
  template:
    metadata:
      labels:
        name: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: burnsie7/wcdemo
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_NAME
              value: app_db
            - name: DATABASE_USER
              value: app_db_user
            - name: DATABASE_PASSWORD
              value: app_db_pw
            - name: IS_BEAT
              value: "true"
          ports:
            - containerPort: 5672
