apiVersion: v1
kind: Service
metadata:
  name: dd-agent
  labels:
    run: dd-agent
spec:
  ports:
  - name: dogstatsdport
    port: 8125
    targetPort: 8125
    protocol: UDP
  - name: traceagentport-udp
    port: 8126
    targetPort: 8126
    protocol: UDP
  - name: traceagentport-tdp
    port: 8126
    targetPort: 8126
    protocol: TCP
  selector:
    app: dd-agent
  type: ClusterIP
