apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        service-discovery.datadoghq.com/redis.check_names: '["redisdb"]'
        service-discovery.datadoghq.com/redis.init_configs: '[{}]'
        service-discovery.datadoghq.com/redis.instances: '[{"host": "%%host%%","port":"%%port%%"}]'
      labels:
        role: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    role: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    role: redis
