# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=100)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Maker')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Widget'),
        ),
        migrations.AlterUniqueTogether(
            name='widget',
            unique_together=set([('name', 'cost')]),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set([('name', 'order_date')]),
        ),
    ]
